environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - npm run test:only
